# Build, increment patch number and publish
patch: build
  yarn version --patch
  @just publish

publish:
  cd dist && npm publish

build: 
  rm -dr dist || :
  yarn run build
  @just copy

copy:
  cp package.json dist
  cp tsconfig.json dist
  cp README.md dist

# Install a package as both --dev and --peer
extra PACKAGE:
  yarn add --peer {{PACKAGE}} && yarn add --dev {{PACKAGE}}